### ISSUE TITLE
Python package seems broken

### ISSUE THREAD

**Issue by bjesus** [browsermt/bergamot-translator#471]
I can't seem to figure out how to use the python package, and I suspect it's broken.

```
❯ bergamot download

❯ bergamot ls
Available models:

```

It never seem to find any model or to let you download any model.

**Comment by bjesus** [comment]
I've managed to found some models by going to https://translatelocally.com/models.json

However installing one seems to be looking for a config file at the wrong place:
```
Downloading and extracting en-bg-tiny into ... /home/bjesus/.local/share/bergamot/models/browsermt/enbg.student.tiny11.v1.3ea060c1b76470a7 Traceback (most recent call last):
  File "/home/bjesus/.local/share/virtualenvs/cdYi8Rg/bin/bergamot", line 8, in <module>
    sys.exit(main())
  File "/home/bjesus/.local/share/virtualenvs/ycdYi8Rg/lib/python3.9/site-packages/bergamot/__main__.py", line 13, in main
    CMDS[args.action].execute(args)
  File "/home/bjesus/.local/share/virtualenvs/ycdYi8Rg/lib/python3.9/site-packages/bergamot/cmds.py", line 133, in execute
    REPOSITORY.download(args.repository, args.model)
  File "/home/bjesus/.local/share/virtualenvs/ycdYi8Rg/lib/python3.9/site-packages/bergamot/repository.py", line 195, in download
    self.repositories.get(name, self.default_repository).download(model_identifier)
  File "/home/bjesus/.local/share/virtualenvs/ycdYi8Rg/lib/python3.9/site-packages/bergamot/repository.py", line 145, in download
    patch_marian_for_bergamot(config_path, bergamot_config_path)
  File "/home/bjesus/.local/share/virtualenvs/ycdYi8Rg/lib/python3.9/site-packages/bergamot/utils.py", line 32, in patch_marian_for_bergamot
    with open(marian_config_path) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bjesus/.local/share/bergamot/models/browsermt/en-bg-tiny/config.intgemm8bitalpha.yml'
```

The file it's looking for seem to be at `~/.local/share/bergamot/models/browsermt/enbg.student.tiny11` instead.

**Comment by bjesus** [comment]
This fixes a bug with downloading: https://github.com/browsermt/bergamot-translator/pull/472

**Comment by bunburya** [comment]
#474 is intended to fix another bug with downloading models.

#472 works well with the default `browsermt` repo but it has issues with the `opus` repo as files are named differently there. For example the `eng-fin-tiny` model has the filename `eng-fin.transformer-tiny11.tar.gz`. So removing everything after the third `.` gives you `eng-fin.transformer-tiny11.tar` which is not the name of the extracted directory. I'm not sure if there is any one-size-fits-all solution though, if different repos follow different file naming conventions for their models. Maybe there should be a separate `Repository` subclass for `opus` which defines different name-stripping logic.
